### ISSUE TITLE
Missing Fy_XY_grid2.csv file 

### ISSUE THREAD

**Issue by jpagliaccio** [zaman13/Brownian-dynamics-in-a-time-varying-force-field#1]
Great work. Both the "Optical trap example" and the "Moving DEP example" code is running fine in Python3. The "Cell separation example" is missing the force data file: Fy_XY_grid2.csv. Is that file available still? Thanks.

**Comment by zaman13** [comment]
Thank you! The file has been added to the repository. It's inside the version 1.9.1 folder.
